module.exports = [
      {
        id: "100",
        farm_id: "1000",
        product: "Beef",
        category: "Meat",
      },
      {
        id: "101",
        farm_id: "1000",
        product: "Lamb",
        category: "Meat",
      },
      {
        id: "102",
        farm_id: "1000",
        product: "Milk",
        category: "Dairy",
      },
      {
        id: "103",
        farm_id: "1000",
        product: "Butter",
        category: "Dairy",
      },
      {
        id: "104",
        farm_id: "1000",
        product: "Apples",
        category: "Fruits",
      },
      {
        id: "105",
        farm_id: "1000",
        product: "Oranges",
        category: "Fruits",
      },
      {
        id: "154",
        farm_id: "1000",
        product: "Potatoes",
        category: "Vegetables",
      },
      {
        id: "155",
        farm_id: "1000",
        product: "Tomatoes",
        category: "Vegetables",
      },
  
      {
        id: "106",
        farm_id: "1001",
        product: "Milk",
        category: "Dairy",
      },
      {
        id: "107",
        farm_id: "1001",
        product: "Butter",
        category: "Dairy",
      },
      {
        id: "108",
        farm_id: "1001",
        product: "Sour Cream",
        category: "Dairy",
      },
      {
        id: "109",
        farm_id: "1001",
        product: "Yogurt",
        category: "Dairy",
      },
  
      {
        id: "110",
        farm_id: "1002",
        product: "Beef",
        category: "Meat",
      },
      {
        id: "111",
        farm_id: "1002",
        product: "Lamb",
        category: "Meat",
      },
      {
        id: "112",
        farm_id: "1002",
        product: "Pork",
        category: "Meat",
      },
      {
        id: "113",
        farm_id: "1002",
        product: "Chicken",
        category: "Meat",
      },
      {
        id: "114",
        farm_id: "1002",
        product: "Turkey",
        category: "Meat",
      },
      {
        id: "115",
        farm_id: "1002",
        product: "Eggs",
        category: "Meat",
      },
  
      {
        id: "116",
        farm_id: "1003",
        product: "Berries",
        category: "Fruits",
      },
      {
        id: "117",
        farm_id: "1003",
        product: "Grapes",
        category: "Fruits",
      },
      {
        id: "118",
        farm_id: "1003",
        product: "Plums",
        category: "Fruits",
      },
      {
        id: "119",
        farm_id: "1003",
        product: "Apples",
        category: "Fruits",
      },
  
      {
        id: "120",
        farm_id: "1004",
        product: "Onions",
        category: "Vegetables",
      },
      {
        id: "121",
        farm_id: "1004",
        product: "Cucumbers",
        category: "Vegetables",
      },
      {
        id: "122",
        farm_id: "1004",
        product: "Carrots",
        category: "Vegetables",
      },
      {
        id: "123",
        farm_id: "1004",
        product: "Potatoes",
        category: "Vegetables",
      },
      {
        id: "124",
        farm_id: "1004",
        product: "Tomatoes",
        category: "Vegetables",
      },
  
      {
        id: "125",
        farm_id: "1005",
        product: "Tomatoes",
        category: "Vegetables",
      },
      {
        id: "126",
        farm_id: "1005",
        product: "Carrots",
        category: "Vegetables",
      },
      {
        id: "127",
        farm_id: "1005",
        product: "Garlic",
        category: "Vegetables",
      },
      {
        id: "128",
        farm_id: "1005",
        product: "Celery",
        category: "Vegetables",
      },
      {
        id: "129",
        farm_id: "1005",
        product: "Chicken",
        category: "Meat",
      },
      {
        id: "130",
        farm_id: "1005",
        product: "Eggs",
        category: "Meat",
      },
  
      {
        id: "131",
        farm_id: "1006",
        product: "Avocados",
        category: "Fruits",
      },
      {
        id: "132",
        farm_id: "1006",
        product: "Mangos",
        category: "Fruits",
      },
      {
        id: "133",
        farm_id: "1006",
        product: "Plums",
        category: "Fruits",
      },
      {
        id: "134",
        farm_id: "1006",
        product: "Apples",
        category: "Fruits",
      },
      {
        id: "135",
        farm_id: "1006",
        product: "Oranges",
        category: "Fruits",
      },
  
      {
        id: "136",
        farm_id: "1007",
        product: "Peaches",
        category: "Fruits",
      },
      {
        id: "137",
        farm_id: "1007",
        product: "Radish",
        category: "Vegetables",
      },
      {
        id: "138",
        farm_id: "1007",
        product: "Mushrooms",
        category: "Vegetables",
      },
      {
        id: "139",
        farm_id: "1007",
        product: "Avocados",
        category: "Fruits",
      },
      {
        id: "140",
        farm_id: "1007",
        product: "Mangos",
        category: "Fruits",
      },
      {
        id: "141",
        farm_id: "1007",
        product: "Oranges",
        category: "Fruits",
      },
      {
        id: "142",
        farm_id: "1007",
        product: "Garlic",
        category: "Vegetables",
      },
  
      {
        id: "143",
        farm_id: "1008",
        product: "Chicken",
        category: "Meat",
      },
      {
        id: "144",
        farm_id: "1008",
        product: "Eggs",
        category: "Meat",
      },
      {
        id: "145",
        farm_id: "1008",
        product: "Beef",
        category: "Meat",
      },
      {
        id: "146",
        farm_id: "1008",
        product: "Pork",
        category: "Meat",
      },
  
      {
        id: "147",
        farm_id: "1009",
        product: "Lamb",
        category: "Meat",
      },
      {
        id: "148",
        farm_id: "1009",
        product: "Turkey",
        category: "Meat",
      },
      {
        id: "149",
        farm_id: "1009",
        product: "Oranges",
        category: "Fruits",
      },
      {
        id: "150",
        farm_id: "1009",
        product: "Mushrooms",
        category: "Vegetables",
      },
      {
        id: "151",
        farm_id: "1009",
        product: "Potatoes",
        category: "Vegetables",
      },
      {
        id: "152",
        farm_id: "1009",
        product: "Tomatoes",
        category: "Vegetables",
      },
      {
        id: "153",
        farm_id: "1009",
        product: "Apples",
        category: "Fruits",
      },
  ];