module.exports = [
      {
        id: "1000",
        farm_name: "Maplewood Farm",
        address: "405 Seymour River Place North",
        city: "Vancouver",
        owner: "Emily Johnson",
        contact_phone: "+1 (604) 929-5610",
        website: "maplewoodfarm.bc.ca",
        promotion: "BOGO",
      },
      {
        id: "1001",
        farm_name: "Southlands Heritage Farm",
        address: "6767 Balaclava Street",
        city: "Vancouver",
        owner: "Michael Williams",
        contact_phone: "+1 (604) 261-1295",
        website: "southlandsfarm.ca",
        promotion: "Dairy 30% off",
      },
      {
        id: "1002",
        farm_name: "United Poultry Company",
        address: "534 Cordova Street E",
        city: "Vancouver",
        owner: "Olivia Davis",
        contact_phone: "+1 (604) 255-9308",
        website: "unitedpoultry.ca",
        promotion: "Meat 20% off",
      },
      {
        id: "1003",
        farm_name: "Nijjer Berry Farms",
        address: "6271 Number 5 Road",
        city: "Richmond",
        owner: "Ethan Martinez",
        contact_phone: "+1 (604) 276-0044",
        website: "nijjerberryfarms.ca",
        promotion: "Berries 10% off",
      },
      {
        id: "1004",
        farm_name: "GJ Farms",
        address: "11020 No. 4 Road",
        city: "Richmond",
        owner: "Ava Thompson",
        contact_phone: "+1 (604) 272-4033",
        website: "gjfarms.ca",
        promotion: "Vegetables 40% off",
      },
      {
        id: "1005",
        farm_name: "Vancouver Food Pedalers Cooperative",
        address: "53 Prior Street",
        city: "Vancouver",
        owner: "Liam Anderson",
        contact_phone: "+1 (604) 500-2438",
        website: "foodpedalers.ca",
        promotion: "BOGO",
      },
      {
        id: "1006",
        farm_name: "Tugwell Creek Farm",
        address: "8750 W Coast Road Sooke",
        city: "Victoria",
        owner: "Sophia Rodriguez",
        contact_phone: "+1 (250) 642-1956",
        website: "tugwellcreekfarm.com",
        promotion: "25% Fruits off",
      },
      {
        id: "1007",
        farm_name: "G.S. Farm",
        address: "11400 4 Road",
        city: "Richmond",
        owner: "Noah Miller",
        contact_phone: "+1 (604) 454-4411",
        website: "gsfarm.ca",
        promotion: "Fruits and Vegetables 10% off",
      },
      {
        id: "1008",
        farm_name: "Sunshine Farms",
        address: "128-8860 No. 1 Road",
        city: "Richmond",
        owner: "Isabella Mitchell",
        contact_phone: "+1 (646) 123-1234",
        website: "sunshinefarms.ca",
        promotion: "Meat 15% off",
      },
      {
        id: "1009",
        farm_name: "Soilnix Farming",
        address: "8111 No 5 Road",
        city: "Richmond",
        owner: "Jackson Wilson",
        contact_phone: "+1 (778) 288-2712",
        website: "soilnix.com",
        promotion: "BOGO",
      },
    ];
  